[build]
  command = "npm install -g pnpm && pnpm install --no-frozen-lockfile && cd example && pnpm install --no-frozen-lockfile && pnpm build"
  publish = "example/dist"

[build.environment]
  NODE_VERSION = "20"
