name: CI Setup
description: Setup pnpm, Node.js, and install dependencies
runs:
  using: composite
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5

    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        node-version: 24
        cache: pnpm
        cache-dependency-path: |
          pnpm-lock.yaml
          example/pnpm-lock.yaml
          example-rspress/pnpm-lock.yaml

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
